# Generated by Django 4.2.6 on 2025-01-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage1',
        ),
    ]
